# Site settings
title: Rachel G. Riskind
email: riskindrg@guilford.edu
description: > # this means to ignore newlines until "baseurl:"
  Professional website of Rachel G. Riskind, Assistant Professor of Psychology at Guilford College in Greensboro, North Carolina.
baseurl: "/psy/riskindrg" # the subpath of your site, e.g. /blog/
url: "http://class.guilford.edu" # the base hostname & protocol for your site
twitter_username: rachelriskind
github_username:  rachelriskind

# Build settings
markdown: kramdown
